[project]
name = "ml-guided-cyber-security"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "deepeval>=3.7.9",
    "litellm>=1.80.16",
    "python-dotenv>=1.2.1",
]
